# Generated by Django 4.0.3 on 2022-05-29 10:20

import canapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=250)),
                ('branch_code', models.CharField(max_length=250)),
                ('front_view', models.FileField(upload_to=canapp.models.update_filename1)),
                ('back_view', models.FileField(upload_to=canapp.models.update_filename2)),
                ('top_view', models.FileField(upload_to=canapp.models.update_filename3)),
            ],
        ),
    ]
